### ISSUE TITLE
Update `Router` section with the new rc router

### ISSUE THREAD

**Issue by lokeshjain2008** [rangle/ngcourse#93]
Hi team,

[NGCourse]() is a amazing book. This book is like best thing on internet for Angular2.
This is our officially accepted book.
But this book is getting updated as the angular2 is changing.
Please update at least `router` part.

**Comment by rpdasilva** [comment]
@lokeshjain2008 This issue may have gone unnoticed due to being in our older Angular 1.x training repository.

If you still find some information lacking, please feel free to open an issue on our ngcourse2 repository
https://github.com/rangle/ngcourse2

Closing this issue as our Angular 2 material has been updated many times since.
